name: "Build and Publish"

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
  page_build:
  release:
    types:
      - created

jobs:
  build-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./site

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run build

      - name: Zip web app artifacts
        run: zip -r release-${{ github.ref_name }}-${{ github.sha }}.zip out

      - name: Release zipped web app artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-${{ github.ref_name }}-${{ github.sha }}.zip

      - name: Archive web app artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-artifacts
          path: 'site/out'

  build-api:
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download web artifacts
        uses: actions/download-artifact@v2
        with:
          name: web-artifacts

      - name: Build
        run: go build -v -o tft-leaderboard

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: 'tft-leaderboard'

      - name: Archive api binary
        uses: actions/upload-artifact@v2
        with:
          name: api-binary
          path: 'tft-leaderboard'

  docker:
    runs-on: ubuntu-latest
    needs:
      - build-app
      - build-api
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/cocoastorm/tft-leaderboard
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to the Github Container registry
        if: github.event.name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download web artifacts
        uses: actions/download-artifact@v2
        with:
          name: web-artifacts
          path: 'site/out'

      - name: Download api artifacts
        uses: actions/download-artifact@v2
        with:
          name: api-binary
          path: 'tft-leaderboard'

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
